name: Smoke Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create test database (SQLite)
        run: |
          echo "CRYPTO_DB_URL=sqlite:///./ci-test.db" >> $GITHUB_ENV

      - name: Run SQL integration tests
        env:
          CRYPTO_DB_URL: ${{ env.CRYPTO_DB_URL }}
        run: pytest -q tests/sql/

      - name: Build Docker image
        run: docker build -t crypto-lake:ci .

      - name: Test Docker image
        run: |
          docker run --rm crypto-lake:ci --help || echo "Image runs successfully"
